version: "2"
linters:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      - path: internal/adapters/rest/.*\.go
        linters:
          - errcheck
formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gofumpt:
        module-path: github.com/hesampakdaman/wallet-service
    golines:
        max-len: 100
    goimports:
      local-prefixes:
        - github.com/hesampakdaman/wallet-service
